name: Lint & Test

on:
  pull_request:
    branches:
    - main

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    name: Build, Lint & Test Codebase
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: make build
    - name: Lint
      run: make lint
    - name: Test
      run: make test
